### ISSUE TITLE
Blank selector values prevent total from appearing

### ISSUE THREAD

**Issue by Toutouwai** [teppokoivula/ListerCalculator#1]
Thanks for this new module @teppokoivula!

I noticed a couple of issues when I was trying it out.

1\. When there are preconfigured but empty filter rows for a Lister Pro instance this results in a selector like "template=68, title%=, integer_1=, ...". The module uses this selector and the blank selector values causes it to match no pages. The solution could be to use `ProcessPageLister::removeBlankSelectors($selector)` to remove those blank selector clauses before the selector is used in `findRaw()`.

2\. I get a warning from Tracy Debugger:
> "Warning: Undefined array key "total" in ...\modules\ListerCalculator\ListerCalculator.module.php:140

**Comment by szabeszg** [comment]
I also always setup Lister Pro listers with empty selectors, so @Toutouwai 's suggestion like this seems to fix it:
```
// get selector
$selector = $event->object->getSelector();
$selector = (new ProcessPageLister)->removeBlankSelectors($selector);
if (empty($selector)) return;
```

As for
_Warning: Undefined array key "total" in ...\modules\ListerCalculator\ListerCalculator.module.php:140_

maybe that's because of a typo at the end of this line:
`$total['no_limits_value'] !== null && $total['no_limits_value'] != $total['total']`
which should be 
`$total['no_limits_value'] !== null && $total['no_limits_value'] != $total['value']
`
instead, perhaps?

Also
`foreach ($totals as $field_name => $totals) {`
?
Why `$totals` is used "twice" here? A different name for the variable for each value would be a better choice, I think.

other issues:

`if ($no_limits_page_ids)...`
is always true because before that the following was already checked:
`!empty($no_limits_page_ids)`

docstring issue:
`@param array $no_limits_page_ids`
should be perhaps:
`@param array|null $no_limits_page_ids`

**Comment by teppokoivula** [comment]
Thanks @Toutouwai and @szabeszg, aforementioned issues should now be fixed in the latest version. Sorry for the delay... and for releasing this module in a very rough shape :)

I'm closing this issue, though please let me know if there's something I missed.
